### ISSUE TITLE
Support for multiple Roles

### ISSUE THREAD

**Issue by gkama** [kamacharovs/aiof-auth#25]
**Overview**
Add support for multiple roles for a user in the JWT. This will include a database changes - schema, etc.

For example, the `roles` object in the JWT should look like this

```json
{
  "iss": "https://www.jerriepelser.com",
  "aud": "blog-readers",
  "sub": "123456",
  "exp": 1499863217,
  "roles": [ "Admin", "SuperUser" ]
}
```

Use it as `[Authorize(Roles = "")]` 

```csharp
public class ValuesController : Controller
{
    [Authorize(Roles = "Admin")]
    [HttpGet("ping/admin")]
    public string PingAdmin()
    {
        return "Pong";
    }
}
```

**Current**
The User and Client entities have a RoleId reference (as a foreign key) to the Role entity. This is a one-to-one relationship

**Solution**
Remove the current relationship between the User, Client and Role entities. Create 2 new entities - UserRole and ClientRole. These will store a one-to-many relationship between a UserId / ClientId and RoleId

**Task breakdown**
When all tasks are completed, then this will reach the definition of done

- [ ] Create separate `UserRole` entity that stores `UserId` and `RoleId`. Foreign keys from `User` and `Role` entities
- [ ] Create separate `ClientRole` entity that stores `ClientId` and `RoleId`. Foreign keys from `Client` and `Role` entities
- [ ] Populate `UserRole` and `ClientRole` entities and PostgreSQL tables
- [ ] Add functionality to get the many roles stored in the entities
- [ ] Add those claims in the JWT generation and is returned to the end-user
- [ ] Feature flag?
- [ ] Remove `RoleId` from `User` entity
- [ ] Remove `RoleId` from `Client` entity
- [ ] Add / update unit tests
- [ ] Perform integration tests
